<?php 
	$dodajLink = $this->url('vprasanje', array('action' => 'dodaj'));
?>
<h1>Vprašanja</h1>
<div id="top-menu">
    <a class="btn btn-primary" href="<?= $dodajLink ?>" id="dodaj-vprasanje">Dodaj</a>
</div>
<div id="user-menu"></div>
<br />
<table class="table">
	<tr>
		<th>Naslov</th>
		<th>Avtor</th>
		<th>Datum objave</th>
	</tr>
	<?php foreach ($vprasanja as $vprasanje): ?>
	<?php $link = $this->url('preglej', array('action' => 'preglej', 'id' => $vprasanje->id)) ?>
	<tr>
		<td><a href="<?= $link ?>"><?= $this->escapeHtml($vprasanje->naslov) ?></a></td>
		<td><?= $this->escapeHtml($vprasanje->user) ?></td>
		<td><?= $this->dateFormat($vprasanje->datum_objave, IntlDateFormatter::MEDIUM) ?></td>
	</tr>
	<?php endforeach; ?>
</table>