<?php
    $ime = ($vprasanje->user == null) ? $vprasanje->avtor : $vprasanje->user->getPolnoIme();
?>

<?php if ($this->imaPravico('odgovor_dodaj') && ($vprasanje->user)): ?>
    <div class="btn-toolbar">
        <a href="#odgovori" class="btn btn-primary"><i class="icon-pencil icon-white"></i> Odgovori</a>
        <button class="btn"><i class="icon-star"></i> Označi</button> 
    </div>
<?php endif ?>

<!-- Vprašanje -->
<div class="well well-small">
    <h3><?= $this->escapeHtml($vprasanje->naslov) ?></h3>
    <p><?= $vprasanje->vsebina ?></p>

    <p>
        <i class="icon-user"></i> <a href="#"><?= $this->escapeHtml($ime) ?></a>
        | <i class="icon-calendar"></i> <?= $this->dateFormat($vprasanje->datum_objave, IntlDateFormatter::MEDIUM, IntlDateFormatter::SHORT) ?>
        | <i class="icon-comment"></i> <a href="#"><?= count($vprasanje->komentarji) ?> odgovorov</a>
        | Rating: <?= $this->rating ?>

        <?php if (count($vprasanje->oznake) > 0): ?>
            | <i class="icon-tags"></i> Oznake:
            <?php foreach ($vprasanje->oznake as $oznaka): ?>
                <a href="#"><span class="label label-info"><?= $oznaka->naslov ?></span></a>
            <?php endforeach ?>
        <?php endif ?>

        <?php if ($this->imaPravico('vprasanje_uredi', $vprasanje->user) && ($vprasanje->user)): ?>
            | <a href="<?= $this->url('vprasanje', array('action' => 'uredi', 'id' => $vprasanje->id)) ?>">
              <?= $this->translate("Uredi") ?></a>
        <?php endif ?>

        <?php if ($this->imaPravico('vprasanje_brisi', $vprasanje->user) && ($vprasanje->user)): ?>
            | <a href="<?= $this->url('vprasanje', array('action' => 'brisi', 'id' => $vprasanje->id)) ?>">
              <?= $this->translate("Briši") ?></a>
        <?php endif ?>

        <?php if ($this->imaPravico('vprasanje_vote') && ($vprasanje->user)): ?>
            <?php if ($this->has_rated): ?>
                | <a href="<?= $this->url('vprasanje', array('action' => 'unvote', 'id' => $vprasanje->id)) ?>">
                  <?= $this->translate("-1") ?></a>
            <?php else: ?>
                | <a href="<?= $this->url('vprasanje', array('action' => 'vote', 'id' => $vprasanje->id)) ?>">
                  <?= $this->translate("+1") ?></a>
            <?php endif ?>
        <?php endif ?>
    </p>
</div>

<!-- Odgovori -->
<hr />
<?php if (count($vprasanje->komentarji) === 0): ?>
    <h5>Vprašanje še nima odgovorov.</h5>
<?php endif ?>
<?php foreach ($vprasanje->komentarji as $odgovor): ?>
    <?= $this->partial('odgovor/pregled', array(
        'odgovor' => $odgovor,
        'rating' => ($odgovor->users_rated == null) ? $odgovor->rating : count($odgovor->users_rated),
        'has_rated' => ($odgovor->users_rated == null) ? null : $odgovor->users_rated->contains($this->user)
    )) ?>
<?php endforeach ?>

<!-- Form -->
<?php if ($this->imaPravico('odgovor_dodaj') && ($vprasanje->user)): ?>
    <hr />
    <h3>Napiši odgovor</h3>
    <a id="odgovori"></a>
    <?= $this->formTwb($this->form, \DluTwBootstrap\Form\FormUtil::FORM_TYPE_VERTICAL) ?>
<?php endif ?>
