<div class="btn-toolbar">
    <a href="#odgovori" class="btn btn-primary"><i class="icon-pencil icon-white"></i> Odgovori</a>
    <button class="btn"><i class="icon-star"></i> Označi</button> 
</div>

<!-- Vprašanje -->
<div class="well well-small">
    <h3><?= $this->escapeHtml($vprasanje->naslov) ?></h3>
    <p><?= $vprasanje->vsebina ?></p>

    <p>
        <i class="icon-user"></i> <a href="#"><?= $this->escapeHtml($vprasanje->user->getPolnoIme()) ?></a>
        | <i class="icon-calendar"></i> <?= $this->dateFormat($vprasanje->datum_objave, IntlDateFormatter::MEDIUM, IntlDateFormatter::SHORT) ?>
        | <i class="icon-comment"></i> <a href="#"><?= count($vprasanje->komentarji) ?> odgovorov</a>

        <?php if (count($vprasanje->oznake) > 0): ?>
            | <i class="icon-tags"></i> Oznake:
            <?php foreach ($vprasanje->oznake as $oznaka): ?>
                <a href="#"><span class="label label-info"><?= $oznaka->naslov ?></span></a>
            <?php endforeach ?>
        <?php endif ?>

        <?php if($this->isGranted('vprasanje_uredi') || $this->jeAvtor($vprasanje->user)): ?>
            | <a href="<?= $this->url('vprasanje', array('action' => 'uredi', 'id' => $vprasanje->id)) ?>"><?= $this->translate("Uredi") ?></a>
        <?php endif ?>

        <?php if($this->isGranted('vprasanje_brisi') || $this->jeAvtor($vprasanje->user)): ?>
            | <a href="<?= $this->url('vprasanje', array('action' => 'brisi', 'id' => $vprasanje->id)) ?>"><?= $this->translate("Briši") ?></a>
        <?php endif ?>
    </p>
</div>

<!-- Odgovori -->
<hr />
<?php if (count($vprasanje->komentarji) === 0): ?>
    <h5>Vprašanje še nima odgovorov.</h5>
<?php endif ?>
<?php foreach ($vprasanje->komentarji as $odgovor): ?>
    <?= $this->partial('odgovor/pregled', array('odgovor' => $odgovor)) ?>
<?php endforeach ?>

<!-- Form -->
<?php if ($this->isGranted('odgovor_dodaj')): ?>
    <hr />
    <h3>Napiši odgovor</h3>
    <a id="odgovori"></a>
    <?= $this->formTwb($this->form, \DluTwBootstrap\Form\FormUtil::FORM_TYPE_VERTICAL) ?>
<?php endif ?>
