<h1>Pregled uporabnika <i><?=$user->username?></i></h1>

<?php if ($this->isGranted('user_uredi')): ?>
    <a class="btn btn-primary" href="<?php echo $this->url('user', array('action' => 'edit', 'id' => $user->id)); ?>" id="uredi-user">Uredi</a>
<?php endif; ?>
<br /><br />
<table class="table">
    <tr>
        <th>Ime</th>
        <td><?=$user->ime?></td>
    </tr>
    <tr>
        <th>Priimek</th>
        <td><?=$user->priimek?></td>
    </tr>
    <tr>
        <th>Email</th>
        <td><?=$user->email?></td>
    </tr>
    <?= ($this->isGranted('user_pregled')) ? '<tr><th>Vpisna številka</th><td>' . $user->vpisna_st . '</td></tr>' : null ?>
    <?= (!empty($user->naslov)) ? '<tr><th>Naslov</th><td>' . $user->naslov . '</td></tr>' : null ?>
    <?= (!empty($user->mesto)) ? '<tr><th>Mesto</th><td>' . $user->mesto . '</td></tr>' : null ?>
    <?= (!empty($user->drzava)) ? '<tr><th>Država</th><td>' . $user->drzava . '</td></tr>' : null ?>
    <?= (!empty($user->opis)) ? '<tr><th>Opis</th><td>' . $user->opis . '</td></tr>' : null ?>
    <?= (!empty($user->splet)) ? '<tr><th>Spletna stran</th><td><a href="http://' . $user->splet . '">' . $user->splet . '</a></td></tr>' : null ?>
    <?= (!empty($user->telefon)) ? '<tr><th>Telefon</th><td>' . $user->telefon . '</td></tr>' : null ?>
    <tr>
        <th>Datum zadnje prijave</th>
        <td><?= $this->dateFormat($user->datum_logina, IntlDateFormatter::LONG, IntlDateFormatter::NONE, 'sl_SI') ?></td>
    </tr>
    
</table>