<h1>Dobrodošli v prokrastinatu</h1>
<hr/>
<h2>Novice</h2>

<?php foreach($novice as $novica): ?>
    <div class="well well-small">
        <b> <?= $this->escapeHtml($novica->datum_objave->format('d-m-Y')); ?></b> 
        <b><a href="<?= $this->url('novice', array('action' => 'view', 'id' => $novica->id));?>"> <?= $novica->naslov; ?> </a><br />
        <p><?= ($novica->vsebina); ?></p>
    </div>
<?php endforeach; ?>
<a class='btn btn-primary' href='<?= $this->url('novice')?>'>Vse novice</a>

