<h1>Dobrodošli v prokrastinatu</h1>
<hr/>
<h2>Oglasna deska</h2>

<?php foreach($oglasi as $oglas): ?>
    <div class="izpisi-oglas">
        <b>Avtor:</b> <a href="<?= $this->url('user', array('action' => 'view', 'id' => $oglas->user->id));?>"> <?= $this->escapeHtml($oglas->user->getPolnoIme()); ?> </a><br />
        <b>Datum:</b> <?= $this->escapeHtml($oglas->datum_objave->format('d-m-Y')); ?> <br />
        <b>Zapade: </b> <?= $this->escapeHtml($oglas->datum_zapadlosti->format('d-m-Y')); ?> <br />
        <b>Kategorija: </b> <?= $this->escapeHtml($oglas->kategorija); ?> <br /><br />
        <p><?= $this->escapeHtml($oglas->vsebina); ?></p>
    </div>
<?php endforeach; ?>
<a class='btn btn-primary' href='<?= $this->url('deska')?>'>Vsi oglasi</a>

