<h1>Zemljevid učilnic</h1>

<?php
    $this->form->prepare();
    echo $this->formTwb($this->form, \DluTwBootstrap\Form\FormUtil::FORM_TYPE_VERTICAL);
?>

<script type="text/javascript">
window.onload = function () {
    $("#select-zemljevid").change(function () {
        url = document.URL + "/get-ucilnice/" + $("#select-zemljevid").val();
        $.getJSON(url, function(data) {
            $('#select-ucilnica').empty();
            for (var uc_id in data.ucilnice) {
                var opt = $('<option />', {
                    value: uc_id,
                    text: data.ucilnice[uc_id]
                });
                $('#select-ucilnica').append(opt);
            }
        });
    });
};
</script>

<?php if($map != null): ?>
<div style="position: relative; top: 0; left: 0">
    <img src="/img/<?=$map->pot ?>" style="position: absolute; top: 0; left: 0; max-width: none;">
    <?php if($room != null): ?>
    <img src="/img/map/krog.png" style="position: absolute; top: <?=$room->top ?>px; left: <?=$room->left ?>px; max-width: none">
    <?php endif; ?>
</div>
<?php endif; ?>


