<h1>Zemljevid učilnic</h1>

<?php
    $this->form->prepare();
    echo $this->formTwb($this->form, \DluTwBootstrap\Form\FormUtil::FORM_TYPE_VERTICAL);
?>

<!-- to je samo primerni izris -->
<div style="position: relative; top: 0; left: 0">
    <img src="/img/map/G1-Man.png" style="position: absolute; top: 0; left: 0; max-width: none;">
    <img src="/img/map/krog.png" style="position: absolute; top: 340px; left: 553px; max-width: none">
</div>


