<?php

$title = 'Izbriši datoteko';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('datoteke', array('action'=>'index'));?>">Vse datoteke</a>
    <a href="<?php echo $this->url('datoteke', array('action'=>'dodaj'));?>">Nalozi datoteko</a>
    <a href="<?php echo $this->url('datoteke', array('action'=>'moje'));?>">Moje datoteke</a>
</p>
<p>Ali ste prepričani, da želite izbrisati datoteko
    <?php echo $this->escapeHtml($datoteke->imeDatoteke); ?> ?
</p>
<?php
$url = $this->url('datoteke', array(
    'action' => 'brisi',
    'id' => $datoteke->id,
    'file' => $datoteke->imeDatoteke,
    
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $datoteke->id; ?>" />
    <input type="submit" name="del" value="Da" class="btn btn-primary"/>
    <input type="submit" name="del" value="Ne" class="btn btn-primary"/>
</div>
</form>