<?php

$title = 'Datoteke';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('datoteke', array('action'=>'index'));?>">Vse datoteke</a>
    <a href="<?php echo $this->url('datoteke', array('action'=>'dodaj'));?>">Nalozi datoteko</a>
    <a href="<?php echo $this->url('datoteke', array('action'=>'moje'));?>">Moje datoteke</a>
</p>
<div id="iskanjeDiv" style="text-align: left; font-weight: bold; font-size: 14px">
<p>
<p>Iskanje datotek</p> 
        <div>
        <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('datoteke', array('action' => 'index')));
            $form->prepare();
            
            echo $this->form()->openTag($form);
            echo $this->formRow($form->get('iskalniNiz')).'<br />';
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
        ?>
    </div>
</div>
<table class="datotekeTable">
<tr>
    <th><a href="?orderBy=imeDatoteke&sort=asc"><img src ="/prokrastinat/public/img/uparrow.png"/></a>Ime datoteke<a href="?orderBy=imeDatoteke&sort=DESC"><img src ="/prokrastinat/public/img/downarrow.png"/></a></th>
    <th><a href="?orderBy=user&sort=asc"><img src ="/prokrastinat/public/img/uparrow.png"/></a>Avtor<a href="?orderBy=avtor&sort=desc"><img src ="/prokrastinat/public/img/downarrow.png"/></a></th>
    <th><a href="?orderBy=opis&sort=asc"><img src ="/prokrastinat/public/img/uparrow.png"/></a>Opis<a href="?orderBy=opis&sort=desc"><img src ="/prokrastinat/public/img/downarrow.png"/></a></th>
    <th><a href="?orderBy=kategorija&sort=asc"><img src ="/prokrastinat/public/img/uparrow.png"/></a>Kategorija<a href="?orderBy=kategorija&sort=desc"><img src ="/prokrastinat/public/img/downarrow.png"/></a></th>
    <th><a href="?orderBy=velikost&sort=asc"><img src ="/prokrastinat/public/img/uparrow.png"/></a>Velikost<a href="?orderBy=velikost&sort=desc"><img src ="/prokrastinat/public/img/downarrow.png"/></a></th>
    <th><a href="?orderBy=datum_uploada&sort=asc"><img src ="/prokrastinat/public/img/uparrow.png"/></a>Datum uploada<a href="?orderBy=datum_uploada&sort=desc"><img src ="/prokrastinat/public/img/downarrow.png"/></a></th>
    <th><a href="?orderBy=st_prenosov&sort=asc"><img src ="/prokrastinat/public/img/uparrow.png"/></a>Preneseno<a href="?orderBy=st_prenosov&sort=desc"><img src ="/prokrastinat/public/img/downarrow.png"/></a></th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($datoteke as $datoteka) : ?>
<tr>
    <td>
        <a href="<?php echo $this->url('datoteke', array('action'=>'pregled', 'id'=>$datoteka->id));?>">
            <?php echo $this->escapeHtml($datoteka->imeDatoteke);?>
        </a>
        <a href="<?php echo $this->url('datoteke', array('action'=>'download', 'id'=>$datoteka->id));?>">
           <img class="ikona" align="right" src ="/prokrastinat/public/img/download.gif"/>
        </a>
    </td>
    <td><?php echo $this->escapeHtml($datoteka->user->getPolnoIme());?></td>
    <td><?php echo $this->escapeHtml($datoteka->opis);?></td>
    <td><?php echo $this->escapeHtml($datoteka->kategorija->ime);?></td>
    <td><?php echo $this->escapeHtml(round($datoteka->velikost/1024/1024, 2));?> MB</td>
    <td><?php echo $this->escapeHtml($datoteka->datum_uploada->format('d-m-Y'));?></td>
    <td><?php echo $this->escapeHtml($datoteka->st_prenosov);?></td>
    <td>
        <?php if (($this->isGranted('datoteke_uredi')) || ($datoteka->user == $this->user)){ ?>
            <a href="<?php echo $this->url('novice', array('action'=>'uredi', 'id'=>$datoteka->id));?>">
                <img class="ikona" src="/prokrastinat/public/img/edit.png"/>
            </a>
            <a href="<?php echo $this->url('novice', array('action'=>'brisi', 'id'=>$datoteka->id));?>">
                <img class="ikona" src="/prokrastinat/public/img/delete.png"/>
            </a>
        <?php } ?>
    </td>
</tr>
<?php endforeach; ?>
</table>