<?php

$title = 'Datoteke';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('datoteke');?>">Vse datoteke</a>
    <a href="<?php echo $this->url('datoteke_dodaj');?>">Nalozi datoteko</a>
    <a href="<?php echo $this->url('datoteke_moje');?>">Moje datoteke</a>
</p>
<div id="iskanjeDiv" style="text-align: left; font-weight: bold; font-size: 14px">
<p>
<p>Iskanje datotek</p> 
        <div>
        <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('datoteke'));
            $form->prepare();
            
            echo $this->form()->openTag($form);
            echo $this->formRow($form->get('iskalniNiz')).'<br />';
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
        ?>
    </div>
</div>
<table class="table table-striped datotekeTable">
<tr>
    <th><a href="?orderBy=imeDatoteke&sort=asc"><i class="icon-chevron-up"></i></a>Datoteka<a href="?orderBy=imeDatoteke&sort=DESC"><i class="icon-chevron-down"></i></a></th>
    <th><a href="?orderBy=user&sort=asc"><i class="icon-chevron-up"></i></a>Avtor<a href="?orderBy=avtor&sort=desc"><i class="icon-chevron-down"></i></a></th>
    <th><a href="?orderBy=kategorija&sort=asc"><i class="icon-chevron-up"></i></a>Kategorija<a href="?orderBy=kategorija&sort=desc"><i class="icon-chevron-down"></i></a></th>
    <th><a href="?orderBy=velikost&sort=asc"><i class="icon-chevron-up"></i></a>Velikost<a href="?orderBy=velikost&sort=desc"><i class="icon-chevron-down"></i></a></th>
    <th><a href="?orderBy=datum_uploada&sort=asc"><i class="icon-chevron-up"></i></a>Datum<a href="?orderBy=datum_uploada&sort=desc"><i class="icon-chevron-down"></i></a></th>
    <th><a href="?orderBy=st_prenosov&sort=asc"><i class="icon-chevron-up"></i></a>Preneseno<a href="?orderBy=st_prenosov&sort=desc"><i class="icon-chevron-down"></i></a></th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($datoteke as $datoteka) : ?>
<tr>
    <td>
        <a href="<?php echo $this->url('datoteke_pregled', array('id'=>$datoteka->id));?>">
            <?php echo $this->escapeHtml($datoteka->imeDatoteke);?>
        </a>
        <a href="<?php echo $this->url('datoteke_download', array('id'=>$datoteka->id));?>">
           <i class="icon-download"></i>
        </a>
    </td>
    <td><?php echo $this->escapeHtml($datoteka->user->getPolnoIme());?></td>
    <td><?php echo $this->escapeHtml($datoteka->kategorija->ime);?></td>
    <td><?php echo $this->escapeHtml(round($datoteka->velikost/1024/1024, 2));?> MB</td>
    <td><?php echo $this->escapeHtml($datoteka->datum_uploada->format('d-m-Y'));?></td>
    <td><?php echo $this->escapeHtml($datoteka->st_prenosov);?></td>
    <td>
        <?php if ($this->imaPravico('datoteke_uredi', $datoteka->user)){ ?>
            <a title="Uredi" href="<?php echo $this->url('datoteke_uredi', array('id'=>$datoteka->id));?>">
                <i class="icon-edit"></i>
            </a>
            <a title="Brisi" class="brisiPotrditev" href="#" data-toggle="modal" data-id="<?php echo $datoteka->id ?>">
                <i class="icon-trash"></i>
            </a>
        <?php } ?>
    </td>
</tr>
<?php endforeach; ?>
</table>

<div id="modal-from-dom" class="modal hide fade">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Briši datoteko</h3>
    </div>
    <div class="modal-body">
        <p>Ali ste prepričani da želite izbrisati to datoteko?</p>
        <p id="debug-url"></p>
    </div>
    <div class="modal-footer">
        <a href="brisi/id" class="btn danger btn-primary">Da</a>
        <a href="javascript:$('#modal-from-dom').modal('hide')" class="btn secondary">Ne</a>
    </div>
</div>