<?php

$title = 'Moje datoteke';
$this->headTitle($title);
$velikost_mb = $velikost/1024/1024;
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('datoteke', array('action'=>'index'));?>">Vse datoteke</a>
    <a href="<?php echo $this->url('datoteke', array('action'=>'dodaj'));?>">Nalozi datoteko</a>
</p>
<div id="kvota" style="text-align: right; font-weight: bold; font-size: 14px">
        <?php echo $this->escapeHtml(round($velikost_mb, 2));?> / 20MB
</div>

<table class="datotekeTable">
<tr>
    <th><a href="?orderBy=imeDatoteke&sort=asc"><img src ="/prokrastinat/public/img/uparrow.png"/></a>Ime datoteke<a href="?orderBy=imeDatoteke&sort=DESC"><img src ="/prokrastinat/public/img/downarrow.png"/></a></th>
    <th><a href="?orderBy=user&sort=asc"><img src ="/prokrastinat/public/img/uparrow.png"/></a>Avtor<a href="?orderBy=avtor&sort=desc"><img src ="/prokrastinat/public/img/downarrow.png"/></a></th>
    <th><a href="?orderBy=opis&sort=asc"><img src ="/prokrastinat/public/img/uparrow.png"/></a>Opis<a href="?orderBy=opis&sort=desc"><img src ="/prokrastinat/public/img/downarrow.png"/></a></th>
    <th><a href="?orderBy=kategorija&sort=asc"><img src ="/prokrastinat/public/img/uparrow.png"/></a>Kategorija<a href="?orderBy=kategorija&sort=desc"><img src ="/prokrastinat/public/img/downarrow.png"/></a></th>
    <th><a href="?orderBy=velikost&sort=asc"><img src ="/prokrastinat/public/img/uparrow.png"/></a>Velikost<a href="?orderBy=velikost&sort=desc"><img src ="/prokrastinat/public/img/downarrow.png"/></a></th>
    <th><a href="?orderBy=datum_uploada&sort=asc"><img src ="/prokrastinat/public/img/uparrow.png"/></a>Datum uploada<a href="?orderBy=datum_uploada&sort=desc"><img src ="/prokrastinat/public/img/downarrow.png"/></a></th>
    <th><a href="?orderBy=st_prenosov&sort=asc"><img src ="/prokrastinat/public/img/uparrow.png"/></a>Preneseno<a href="?orderBy=st_prenosov&sort=desc"><img src ="/prokrastinat/public/img/downarrow.png"/></a></th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($datoteke as $datoteka) : ?>
<tr>
    <td><?php echo $this->escapeHtml($datoteka->imeDatoteke);?>
        <a href="<?php echo $this->url('datoteke', array('action'=>'download', 'id'=>$datoteka->id));?>">
           <img align="right" src ="/prokrastinat/public/img/download.gif"/>
        </a>
    </td>
    <td><?php echo $this->escapeHtml($datoteka->user->getPolnoIme());?></td>
    <td><?php echo $this->escapeHtml($datoteka->opis);?></td>
    <td><?php echo $this->escapeHtml($datoteka->kategorija->ime);?></td>
    <td><?php echo $this->escapeHtml(round($datoteka->velikost/1024/1024, 2));?> MB</td>
    <td><?php echo $this->escapeHtml($datoteka->datum_uploada->format('d-m-Y'));?></td>
    <td><?php echo $this->escapeHtml($datoteka->st_prenosov);?></td>
    <td>
        <a href="<?php echo $this->url('datoteke', array('action'=>'pregled', 'id'=>$datoteka->id));?>">Podrobnosti</a>
        <a href="<?php echo $this->url('datoteke', array('action'=>'uredi', 'id'=>$datoteka->id));?>">Uredi</a>
        <a href="<?php echo $this->url('datoteke', array('action'=>'brisi', 'id'=>$datoteka->id));?>">Briši</a>     
    </td>
</tr>
<?php endforeach; ?>
</table>