<?php

$title = 'Datoteke';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('datoteke', array('action'=>'index'));?>">Vse datoteke</a>
    <a href="<?php echo $this->url('datoteke', array('action'=>'add'));?>">Nalozi datoteko</a>
    <a href="<?php echo $this->url('datoteke', array('action'=>'myfiles'));?>">Moje datoteke</a>
</p>
<div id="iskanjeDiv" style="text-align: left; font-weight: bold; font-size: 14px">
<p>
<p>Iskanje datotek</p> 
    <form  method="post" action="search"  id="iskanjeform"> 
        <input  type="text" name="isci"> <br>
        <input  type="submit" name="submit" value="Isci"> 
    </form> 
</div>
<table class="table">
<tr>
    <th><a href="?orderBy=imeDatoteke&sort=asc"><img src ="http://localhost/prokrastinat/public/img/uparrow.png"/></a>Ime datoteke<a href="?orderBy=imeDatoteke&sort=DESC"><img src ="http://localhost/prokrastinat/public/img/downarrow.png"/></a></th>
    <th><a href="?orderBy=user&sort=asc"><img src ="http://localhost/prokrastinat/public/img/uparrow.png"/></a>Avtor<a href="?orderBy=avtor&sort=desc"><img src ="http://localhost/prokrastinat/public/img/downarrow.png"/></a></th>
    <th><a href="?orderBy=opis&sort=asc"><img src ="http://localhost/prokrastinat/public/img/uparrow.png"/></a>Opis<a href="?orderBy=opis&sort=desc"><img src ="http://localhost/prokrastinat/public/img/downarrow.png"/></a></th>
    <th><a href="?orderBy=velikost&sort=asc"><img src ="http://localhost/prokrastinat/public/img/uparrow.png"/></a>Velikost<a href="?orderBy=velikost&sort=desc"><img src ="http://localhost/prokrastinat/public/img/downarrow.png"/></a></th>
    <th><a href="?orderBy=datum_uploada&sort=asc"><img src ="http://localhost/prokrastinat/public/img/uparrow.png"/></a>Datum uploada<a href="?orderBy=datum_uploada&sort=desc"><img src ="http://localhost/prokrastinat/public/img/downarrow.png"/></a></th>
    <th><a href="?orderBy=st_prenosov&sort=asc"><img src ="http://localhost/prokrastinat/public/img/uparrow.png"/></a>Preneseno<a href="?orderBy=st_prenosov&sort=desc"><img src ="http://localhost/prokrastinat/public/img/downarrow.png"/></a></th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($datoteke as $datoteka) : ?>
<tr>
    <td><?php echo $this->escapeHtml($datoteka->imeDatoteke);?></td>
    <td><?php echo $this->escapeHtml($datoteka->user->getPolnoIme());?></td>
    <td><?php echo $this->escapeHtml($datoteka->opis);?></td>
    <td><?php echo $this->escapeHtml(round($datoteka->velikost/1024/1024, 2));?> MB</td>
    <td><?php echo $this->escapeHtml($datoteka->datum_uploada->format('d-m-Y'));?></td>
    <td><?php echo $this->escapeHtml($datoteka->st_prenosov);?></td>
    <td>
        <a href="<?php echo $this->url('datoteke', array('action'=>'view', 'id'=>$datoteka->id));?>">Podrobnosti</a>
        <a href="<?php echo $this->url('datoteke', array('action'=>'download', 'id'=>$datoteka->id));?>">Prenos</a>   
    </td>
</tr>
<?php endforeach; ?>
</table>