<?php

$title = 'Uredi datoteko';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('datoteke', array('action'=>'index'));?>">Vse datoteke</a>
    <a href="<?php echo $this->url('datoteke', array('action'=>'dodaj'));?>">Naloži datoteko</a>
    <a href="<?php echo $this->url('datoteke', array('action'=>'moje'));?>">Moje datoteke</a>
</p>


<?= $this->formTwb($this->form) ?>
<?php
