<?php

$title = 'Datoteke';
$this->headTitle($title);
$link = $_SERVER['DOCUMENT_ROOT'].$_SERVER['REQUEST_URI'] ;
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('datoteke', array('action'=>'index'));?>">Vse datoteke</a>
    <a href="<?php echo $this->url('datoteke', array('action'=>'add'));?>">Nalozi datoteko</a>
    <a href="<?php echo $this->url('datoteke', array('action'=>'myfiles'));?>">Moje datoteke</a>
</p>
<div class="datotekaView">
    <div style="font:22px Tahoma bold; text-align: center;"><?php echo $datoteke->imeDatoteke;?></div><p>
    <p>
    Avtor: <?php echo $datoteke->user->getPolnoIme() ?><p>
    Opis: <?php echo $datoteke->opis ?><p>
    Datum uploada: <?php echo $datoteke->datum_uploada->format('d-m-Y') ?><p>
    Velikost: <?php echo round($datoteke->velikost/1024/1024, 2) ?> MB<p>
    Ogledi: <?php echo $datoteke->st_ogledov ?><p>
    Prenosi: <?php echo $datoteke->st_prenosov ?><p>
    Kategorija: <?php echo $datoteke->kategorija->ime ?>
    <div class="prenosTextInButton">
        <a href="<?php echo $this->url('datoteke', array('action'=>'download', 'id'=>$datoteke->id));?>" >
            Prenos<img style="width: 25px;" src ="http://localhost/prokrastinat/public/img/download.gif"/>
        </a>
    </div>
</div>
<div>
<a href="http://www.facebook.com/sharer.php?s=100
&p[url]=http://prokrastinat.kreten.si/
&p[images][0]=http://upload.wikimedia.org/wikipedia/commons/c/c5/Logo_FC_Bayern_M%C3%BCnchen.svg
&p[title]=Prokrastinat y0!
&p[summary]=TADAM!">SHARE</a>
</div>