<?php
    $title = 'Izbriši novico';
    $this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Ste prepričani, da želite izbrisati novico 
    '<?php echo $this->escapeHtml($novica->naslov); ?>'
</p>
<?php
$url = $this->url('novice', array(
    'action' => 'brisi',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $novica->id; ?>" />
    <input type="submit" name="del" value="Yes" class="btn btn-primary" />
    <input type="submit" name="del" value="No" class="btn btn-primary" />
</div>
</form>