<?php

$title = 'Novice';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php if ($this->isGranted('novica_dodaj')): ?>
    <p>
    <a href="<?php echo $this->url('novice_dodaj'); ?>" id="dodaj-novico" class="btn btn-large"><i class="icon-plus"></i> Nova novica</a>
    </p>
<?php endif; ?>

<?php foreach ($novice as $novica) : ?>
    <div class="well well-small novica">
        <div class="novicaHeader">
            <b> <?= $this->escapeHtml($novica->datum_objave->format('d-m-Y')); ?></b> 
            <b>
                <a href="<?= $this->url('novice_view', array('id' => $novica->id)) ?>">
                    <?= $novica->naslov; ?>
                </a>
            </b>
            <div class="ikone">
               <?php if ($this->imaPravico('novica_uredi', $novica->user)){ ?>
                <a class="btn btn-mini" href="<?php echo $this->url('novice_uredi', array('id'=>$novica->id));?>">
                    <i class="icon-edit"></i>
                    Uredi
                </a>
                <a class="btn btn-mini" href="<?php echo $this->url('novice_brisi', array('id'=>$novica->id));?>">
                    <i class="icon-remove"></i>
                    Izbriši
                </a>
               <?php } ?>
            </div>
            <br/>
        </div>
        <p class="novicaVsebina">
            <?php if(is_null($novica->opis)){
                        echo $novica->vsebina;
                    } 
                    else{
                        echo $novica->opis;
            } ?>
        </p>
    </div>
<?php endforeach; ?>