<?php

$title = 'Ostale novice';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php if ($this->isGranted('novica_dodaj')): ?>
    <p>
    <a class="btn btn-primary" href="<?php echo $this->url('novice', array('action' => 'parse')); ?>" id="dodaj-novico">Dodaj novice</a>
    </p>
<?php endif; ?>
    
    <div class="well well-small izbiraNovic">
        <a href="studentske/">
            <h1 class="bazaZnanjaNaslov">Študentske novice</h1>
            <div class="ostaleNoviceSlika">
                <img style="float: right;" src="/img/studentske_novice.png"/>
            </div>
        </a>
    </div>
    
    <div class="well well-small">
        <h1><a href="<?= $this->url('novice_extreme', array('action' => 'extreme'))?>">eXtreme Tech novice</a></h1>
    </div>