<?php
function curPageURL() {
 $pageURL = 'http';
 if ($_SERVER["HTTPS"] == "on") {$pageURL .= "s";}
 $pageURL .= "://";
 if ($_SERVER["SERVER_PORT"] != "80") {
  $pageURL .= $_SERVER["SERVER_NAME"].":".$_SERVER["SERVER_PORT"].$_SERVER["REQUEST_URI"];
 } else {
  $pageURL .= $_SERVER["SERVER_NAME"].$_SERVER["REQUEST_URI"];
 }
 return $pageURL;
}
?>
<div class="novicaView">
    <h2><?php echo $novica->naslov ?></h2>
    <div class="novicaJedro">
        <b>Avtor: </b> <?php echo $novica->user->getPolnoIme() ?>
        <br/>
        <b>Datum objave: </b> <?php echo $novica->datum_objave->format('d-m-Y') ?>
        <div class="novicaVsebina">
            <?php echo $novica->vsebina ?>
        </div>
    </div>
</div>
<br/>
<a class='btn btn-primary' href='<?= $this->url('novice', array('action' => 'uredi', 'id' => $novica->id))?>'>Uredi</a>
<a href="https://www.facebook.com/sharer/sharer.php?u=http://localhost/novice/pregled/5" target="_blank">
  Share on Facebook
</a>