<?php function selfURL(){
    if(!isset($_SERVER['REQUEST_URI'])){
        $serverrequri = $_SERVER['PHP_SELF'];
    }else{
        $serverrequri =    $_SERVER['REQUEST_URI'];
    }
    $s = empty($_SERVER["HTTPS"]) ? '' : ($_SERVER["HTTPS"] == "on") ? "s" : "";
    $protocol = strleft(strtolower($_SERVER["SERVER_PROTOCOL"]), "/").$s;
    $port = ($_SERVER["SERVER_PORT"] == "80") ? "" : (":".$_SERVER["SERVER_PORT"]);
    return $protocol."://".$_SERVER['SERVER_NAME'].$port.$serverrequri;   
    }
    
    function strleft($s1, $s2) {
	return substr($s1, 0, strpos($s1, $s2));
    }
    
    ?>
<div class="novicaView">
    <h2><?php echo $novica->naslov ?></h2>
    <div class="novicaJedro">
        <b>Avtor: </b> <?php echo $novica->user->getPolnoIme() ?>
        <br/>
        <b>Datum objave: </b> <?php echo $novica->datum_objave->format('d-m-Y') ?>
        <div class="novicaVsebina">
            <?php echo $novica->vsebina ?>
        </div>
    </div>
</div>
<br/>
<a class='btn btn-primary' href='<?= $this->url('novice', array('action' => 'uredi', 'id' => $novica->id))?>'>Uredi</a>