<div class=" well novicaView novicaPregled">
    <h2><?php echo $novica->naslov ?></h2>
    <div class="novicaJedro">
        <b>Avtor: </b> <?php echo $novica->user->getPolnoIme() ?>
        <br/>
        <b>Datum objave: </b> <?php echo $novica->datum_objave->format('d-m-Y') ?>
        <div class="novicaVsebina">
            <?php echo $novica->vsebina ?>
        </div>
        <br/>
        <b>Vir: </b><a href="<?php echo $novica->vir ?>"><?php echo $novica->vir ?></a>
    </div>
</div>
<br/>
<a class='btn btn-primary' href='<?= $this->url('novice', array('action' => 'uredi', 'id' => $novica->id))?>'>Uredi</a>