<?php
    $title = 'Briši oglas';
    $this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Ste prepričani, da želite izbrisati: 
    '<?php echo $this->escapeHtml($oglas->naslov); ?>' od
    '<?php echo $this->escapeHtml($oglas->user->getPolnoIme()); ?>'?
</p>
<?php
$url = $this->url('deska', array(
    'action' => 'brisi',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $oglas->id; ?>" />
    <input type="submit" name="del" value="Yes" class="btn btn-primary" />
    <input type="submit" name="del" value="No" class="btn btn-primary" />
</div>
</form>