<h1>Oglasna deska</h1>
<div id="top-menu">
<a href="<?php echo $this->url('deska', array('action' => 'dodaj'));?>" id="dodaj-oglas">Dodaj</a>
</div>
<table class="table">
    <tr>
        <th>Naslov</th>
        <th>Vsebina</th>
        <th>Zapade</th>
    </tr>
    <?php foreach ($oglasi as $oglas) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($oglas->getNaslov());?></td>
        <td><?php echo $this->escapeHtml($oglas->getVsebina());?></td>
        <td><?php echo $this->escapeHtml($oglas->getDatumZapadlosti()) ?></td>
    </tr>
    <?php endforeach; ?>
</table>