<h1>Oglasna deska</h1>

<?php if ($this->isGranted('deska_dodaj')): ?>
    <a class="btn btn-primary" href="<?php echo $this->url('deska', array('action' => 'dodaj')); ?>" id="dodaj-oglas">Dodaj oglas</a>
<?php endif; ?>
    <br /> <br />
    
    <div>
        <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('deska', array('action' => 'index')));
            $form->prepare();
            
            echo $this->form()->openTag($form);
            echo $this->formRow($form->get('kategorija')).'<br />';
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
        ?>
    </div> 

<table class="table">
    <tr>
        <th>Naslov</th>
        <th>Avtor</th>
        <th>Datum objave</th>
        <th>Kategorija</th>
        <th>Datum zapadlosti</th>
        <th></th>
    </tr>
    
    <?php foreach ($oglasi as $oglas) : ?>
        <tr>
            <td>
                <a href="<?php echo $this->url('deska', array('action' => 'preglej', 'id' => $oglas->id)); ?>"><?php echo $this->escapeHtml($oglas->naslov); ?></a>
            </td>
            <td><a href="<?= $this->url('user', array('action' => 'view', 'id' => $oglas->user->id))?>"><?= $this->escapeHtml($oglas->user->getPolnoIme()) ?> </a></td>
            <td><?php echo $this->escapeHtml($oglas->datum_objave->format('d.m.Y')) ?></td>
            <td><?php echo $this->escapeHtml($oglas->kategorija->ime) ?></td>
            <td><?php echo $this->escapeHtml($oglas->datum_zapadlosti->format('d.m.Y')) ?></td>
            <?php if ($this->imaPravico('deska_dodaj', $oglas->user)): ?>
                <td>
                    <a href="<?= $this->url('deska', array('action' => 'uredi', 'id' => $oglas->id)); ?>"><i class="icon-edit"></i></a>
                    <!-- <a href="<?= $this->url('deska', array('action' => 'brisi', 'id' => $oglas->id)); ?>"><i class="icon-trash"></i></a> -->
                    <a class="brisiPotrditev" href="#" data-id="<?= $oglas->id?>" role="button" data-toggle="modal"><i class="icon-trash"></i></a>
                </td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
</table>
    
<?php if ($this->isGranted('deska_dodaj')): ?>
    <a class="btn btn-primary" href="<?php echo $this->url('deska', array('action' => 'kategorije')); ?>">Kategorije</a>
<?php endif; ?>

<div id="modal-brisanje" class="modal hide fade">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Briši oglas</h3>
    </div>
    <div class="modal-body">
        <p>Ali ste prepričani da želite izbrisati ta oglas?</p>
        <p id="debug-url"></p>
    </div>
    <div class="modal-footer">
        
        <a href="javascript:$('#modal-brisanje').modal('hide')" class="btn secondary">Ne</a>
        <a href="/deska/brisi/id" class="btn danger btn-primary">Da</a>
    </div>
</div>  