<h1>Oglasna deska</h1>
<div id="top-menu">

<?php if ($this->isGranted('deska_dodaj')): ?>
    <a class="btn btn-primary" href="<?php echo $this->url('deska', array('action' => 'dodaj')); ?>" id="dodaj-oglas">Dodaj</a>
<?php endif; ?>
    <br /> <br />
    
    <div>
        <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('deska', array('action' => 'index', 'id' => $id)));
            $form->prepare();
            
            echo $this->form()->openTag($form);
            echo $this->formRow($form->get('kategorija')).'<br />';
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
        ?>
    </div> 
    
<table class="table">
    <tr>
        <th>Naslov</th>
        <th>Avtor</th>
        <th>Datum objave</th>
        <th>Kategorija</th>
        <th>Datum zapadlosti</th>
        <th></th>
    </tr>
    
    <?php foreach ($oglasi as $oglas) : ?>
        <tr>
            <td>
                <a href="<?php echo $this->url('deska', array('action' => 'preglej', 'id' => $oglas->id)); ?>"><?php echo $this->escapeHtml($oglas->naslov); ?></a>
            </td>
            <td><a href="<?= $this->url('user', array('action' => 'view', 'id' => $oglas->user->id))?>"><?= $this->escapeHtml($oglas->user->getPolnoIme()) ?> </a></td>
            <td><?php echo $this->escapeHtml($oglas->datum_objave->format('d-m-Y')) ?></td>
            <td><?php echo $this->escapeHtml($oglas->kategorija->ime) ?></td>
            <td><?php echo $this->escapeHtml($oglas->datum_zapadlosti->format('d-m-Y')) ?></td>
            <?php if ($this->isGranted('deska_dodaj')): ?>
                <td>
                    <a href="<?= $this->url('deska', array('action' => 'uredi', 'id' => $oglas->id)); ?>">Uredi</a>
                    <a href="<?= $this->url('deska', array('action' => 'brisi', 'id' => $oglas->id)); ?>">Briši</a>
                </td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
</table>