<h3><?= $this->escapeHtml($oglas->naslov) ?></h3>
<hr />
<div id="oglas-osnovni-podatki" class="well well-small">
    <p>
        Avtor: <a href="<?= $this->url('user', array('action' => 'view', 'id' => $oglas->user->id))?>"><?= $this->escapeHtml($oglas->user->getPolnoIme()) ?> </a> <br />
        Datum: <?= $this->escapeHtml($oglas->datum_objave->format('d-m-Y')) ?> <br />
        Zapade: <?= $this->escapeHtml($oglas->datum_zapadlosti->format('d-m-Y')) ?>
    </p>
</div>
<hr />
<div id="oglas-vsebina" class="well well-small">
    <?= $oglas->vsebina ?>
</div>
<hr />
<a class="btn btn-primary" href="<?php echo $this->url('deska');?>">Nazaj</a>