<h3><?= $this->escapeHtml($oglas->naslov) ?></h3>
<hr />
<div id="oglas-osnovni-podatki">
    Avtor: <?= $this->escapeHtml($oglas->user->getPolnoIme()) ?> <br />
    Datum: <?= $this->escapeHtml($oglas->datum_objave->format('d-m-Y')) ?> <br />
    Zapade: <?= $this->escapeHtml($oglas->datum_zapadlosti->format('d-m-Y')) ?>
</div>
<hr />
<div id="oglas-vsebina">
    <?= $this->escapeHtml($oglas->vsebina) ?>
</div>
<hr />
<a class="btn btn-primary" href="<?php echo $this->url('deska');?>">Nazaj</a>