<?php
$title = 'Uredi oglas';
$this->headtitle($title);
?>

<h1>
    <?= $this->escapeHtml($title); ?>
</h1>
<div id="test">
    <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('deska', array('action' => 'uredi', 'id' => $this->id)));
        $form->prepare();

        echo $this->form()->openTag($form);
        echo $this->formRow($form->get('naslov'));
        echo $this->formRow($form->get('datum-zapadlosti'));
        echo $this->formRow($form->get('vsebina'));
        echo "<br />";
        echo $this->formSubmit($form->get('submit'));
        echo $this->form()->closeTag();
    ?>
    <a class="btn btn-primary" href="<?php echo $this->url('deska');?>">Nazaj</a>
</div>