<script>
    window.onload = function() {  
        //$("#Datum").data('datetimepicker').setDate(new Date());
        $('#Datum').datepicker({
            format: 'dd.mm.yyyy'
        });
    };
</script>

<?php
$title = 'Uredi oglas';
$this->headtitle($title);
?>

<h1>
    <?= $this->escapeHtml($title); ?>
</h1>
<div id="test">
    <?php
        /*$form = $this->form;
        $form->setAttribute('action', $this->url('deska', array('action' => 'uredi', 'id' => $this->id)));
        $form->prepare();

        echo $this->form()->openTag($form);
        echo $this->formRow($form->get('naslov'));
        echo $this->formRow($form->get('datum-zapadlosti'));
        echo $this->formRow($form->get('kategorija'));
        echo $this->formRow($form->get('vsebina'));
        echo "<br />";
        echo $this->formSubmit($form->get('submit'));
        echo $this->form()->closeTag();*/
        echo $this->formTwb($this->form, \DluTwBootstrap\Form\FormUtil::FORM_TYPE_VERTICAL);
    ?>
    <a class="btn btn-primary" href="<?php echo $this->url('deska');?>">Nazaj</a>
</div>