<?php

$title = 'Dodaj datoteko';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('datoteke', array('action'=>'index'));?>">Vse datoteke</a>
    <a href="<?php echo $this->url('datoteke', array('action'=>'myfiles'));?>">Moje datoteke</a>
</p>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('datoteke', array('controller'=>'datoteke', 'action' => 'add'))); 
$form->prepare();
 
echo $this->form()->openTag($form);
echo $this->formRow($form->get('opis'));
 
echo $this->formRow($form->get('fileupload'));
 
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();