<?php

$title = 'Datoteke';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('datoteke', array('action'=>'add'));?>">Nalozi datoteko</a>
    <a href="<?php echo $this->url('datoteke', array('action'=>'myFiles'));?>">Moje datoteke</a>
</p>

<table class="table">
<tr>
    <th>Ime datoteke</th>
    <th>Opis</th>
    <th>Nalozeno</th>
    <th>Preneseno</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($datoteke as $datoteka) : ?>
<tr>
    <td><?php echo $this->escapeHtml($datoteka->__get('imeDatoteke'));?></td>
    <td><?php echo $this->escapeHtml($datoteka->__get('opis'));?></td>
    <td><?php echo $this->escapeHtml($datoteka->__get('datum_uploada')->format('d-m-Y'));?></td>
    <td><?php echo $this->escapeHtml($datoteka->__get('st_prenosov'));?></td>
    <td>
        <a href="<?php echo $this->url('datoteke', array('action'=>'download', 'id'=>$datoteka->__get('id')));?>">Prenos</a>
        <a href="<?php echo $this->url('datoteke', array('action'=>'delete', 'id'=>$datoteka->__get('id'), 'file'=>$datoteka->__get('imeDatoteke')));?>">Briši</a>
    </td>
</tr>
<?php endforeach; ?>
</table>