<?php
$url = $this->route;
$parameterGet = $this->Requesthelper();
if ($parameterGet != ""){
  $parameterGet = "?".$parameterGet;
}
?>

<div class="pagination pagination-centered">
    <ul>
        <!-- PREJŠNJA IN PRVA -->
      <?php if (isset($this->previous)): ?>
        <li><a href="<?= $url.'stran/1'; ?>">&laquo;</a></li>&nbsp;
        <li><a href="<?= $url.'stran/'.$this->previous.$parameterGet; ?>">&lt;</a></li>&nbsp;
      <?php else: ?>
        <li class="disabled liStyle"><span>&laquo;</span></li>&nbsp;
        <li class="disabled"><span>&lt;</span></li>&nbsp;
      <?php endif; ?>
        <!-- ŠTEVILKE STRANI -->
      <?php foreach ($this->pagesInRange as $page): ?>
      <?php if ($page != $this->current): ?>
        <li><a href="<?= $url.'stran/'.$page.$parameterGet; ?>">
      <?= $page; ?>
        </li></a>&nbsp;
      <?php else: ?>
        <li class="active"><!-- TRENUTNA -->
         <span><?= $page; ?></span>
         </li>&nbsp;
      <?php endif; ?>
      <?php endforeach; ?>
      <!-- NASLEDNJA IN ZADNJA -->
        <?php if (isset($this->next)): ?>
        <li><a href="<?= $url.'stran/'.$this->next.$parameterGet; ?>">&gt;</a></li>&nbsp;
        <li><a href="<?= $url.'stran/'.$this->pageCount.$parameterGet; ?>">&raquo;</a></li>&nbsp;
      <?php else: ?>
        <li class="disabled"><span>&gt;</span></li>&nbsp;
        <li class="disabled"><span>&raquo;</span></li>&nbsp;
      <?php endif; ?>
    </ul>
</div>