<h1>Profesorji</h1>
<table class="table">
    <tr>
        <th>Priimek</th>
        <th>Ime</th>
    </tr>
    <?php foreach($profesorji as $profesor): ?>
        <tr>
            <td><a href="<?= $this->url('aips', array('action' => 'preglej', 'id' => $profesor->id));?>"><?= $profesor->priimek ?></a></td>
            <td><a href="<?= $this->url('aips', array('action' => 'preglej', 'id' => $profesor->id));?>"><?= $profesor->ime ?></a></td>
        </tr>
    <?php endforeach; ?>
</table>