<?php

$basePath = $this->basePath();
//Twitter Bootstrap styles
$this->headLink()->appendStylesheet($basePath . '/css/bootstrap.min.css');
//Twitter Bootstrap style override by DluTwBootstrap
$this->headLink()->appendStylesheet($basePath . '/css/dlu-tw-bootstrap.css');

//Add your own style here
//$this->headLink()->appendStylesheet($basePath . '/css/style.css');

// Jurijev css override
$this->headLink()->appendStylesheet($basePath . '/css/jurij.css');

// MaTTo css
$this->headLink()->appendStylesheet($basePath .'/css/matto.css');

// Simonov povprečen css
$this->headLink()->appendStylesheet($basePath .'/css/simon.css');

// Damjan css
$this->headLink()->appendStylesheet($basePath .'/css/damjan.css');

//Twitter Bootstrap responsive styles
$this->headLink()->appendStylesheet($basePath . '/css/bootstrap-responsive.min.css');
//jQuery and Twitter Bootstrap JS libraries
$this->inlineScript()->appendFile($basePath . '/js/jquery-1.8.0.min.js');
$this->inlineScript()->appendFile($basePath . '/js/bootstrap.min.js');
// Datepicker
$this->inlineScript()->appendFile($basePath . '/js/bootstrap-datetimepicker.js');
$this->inlineScript()->appendFile($basePath . '/js/bootstrap-datetimepicker.sl.js');
$this->headLink()->appendStylesheet($basePath .'/css/bootstrap-datetimepicker.min.css');

$this->inlineScript()->appendFile($basePath . '/js/bootstrap-datepicker.js');
$this->headLink()->appendStylesheet($basePath .'/css/datepicker.css');

$this->inlineScript()->appendFile($basePath . '/js/tinymce.min.js');

$this->inlineScript()->appendFile($basePath . '/js/prokrastinat.js');

$this->inlineScript()->appendFile($basePath . '/js/damjan.js');

// Urniki
$this->headLink()->appendStylesheet($basePath . '/css/tribal-timetable.css');
$this->inlineScript()->appendFile($basePath . '/js/tribal-timetable.js');

echo $this->doctype(); ?>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('Prokrastinat'))->setSeparator('::')->setAutoEscape(false) ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <!-- link href="/css/bootstrap.min.css" rel="stylesheet"-->
    <?= $this->headLink() ?>
    <?= $this->headStyle() ?>
    <?= $this->headScript() ?>
    
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner navbar-inner-center">
            <div class="container-fluid">
                <a class="brand" href="/">FERI</a>
                <ul class="nav">
                    <li><a href="https://aips.uni-mb.si/">AIPS</a></li>
                    <li class="divider-vertical"></li>
                    <li><a href="http://forum.feri.uni-mb.si/">Forum</a></li>
                    <li class="divider-vertical"></li>
                    <li><a href="https://mail.feri.uni-mb.si/exchweb/bin/auth/owalogon.asp?url=https://mail.feri.uni-mb.si/exchange&reason=0">Webmail</a></li>
                    <li class="divider-vertical"></li>
                    <li><a href="http://www.feri.uni-mb.si/povezava.aspx?pid=224">Eduroam</a></li>
                </ul>
                <div style="float: right;"><?= $this->login_box() ?></div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">
          <div class="sidebar-nav leftSidebar">
            <ul class="nav nav-tabs nav-stacked">
              <li><a href="<?= $this->url('novice') ?>">Novice</a></li>
              <li><a href="<?= $this->url('deska') ?>">Oglasna deska</a></li>
              <li><a href="<?= $this->url('vprasanje') ?>">Vprašanja</a></li>
              <li><a href="<?= $this->url('datoteke') ?>">Datoteke</a></li>
              <li><a href="<?=$this->url('map')?>">Zemljevid</a></li>
              <li><a href="#">Zaposleni</a></li>
              <?php if ($this->isGranted('user_uredi')): ?><li><a href="<?= $this->url('user_list') ?>">Uporabniki</a></li><?php endif; ?>
              <li><a href="<?= $this->url('urniki') ?>">Urniki</a></li>
              <!--<li class="active"><a href="#">Novice</a></li>
              <li><a href="#">Splošne informacije</a></li>
              <li><a href="#">Informacije za študente</a></li>
              <li><a href="#">Informacije za dijake</a></li>
              <li><a href="#">Študijski programi</a></li>
              <li><a href="#">Izredni študij</a></li>
              <li><a href="#">Podiplomski študij</a></li>
              <li><a href="#">Obvladovanje kakovosti</a></li>
              <li><a href="#">Raziskovalna dejavnost</a></li>
              <li><a href="#">Javna naročila</a></li>
              <li><a href="#">Alumni</a></li>-->

              <!-- <li class="nav-header">Sidebar</li> -->
              <li class="dropdown-submenu">
                  <a href="#">Dodatne novice</a>
                  <ul class="dropdown-menu">
                      <li><a href="<?= $this->url('novice_studentske');?>">Študentske novice</a></li>
                      <li><a href="<?= $this->url('novice_iw');?>">InfoWorld novice</a></li>
                      <li><a href="<?= $this->url('novice_extreme', array('action' => 'extreme'));?>">eXtreme novice</a></li>
                  </ul>
              </li>
              <li><a href="<?= $this->url('iskanje') ?>">Iskanje</a></li>

              <li class="nav-header">Inštituti</li>
              <li><a href="http://www.au.feri.uni-mb.si/">Inštitut za avtomatiko</a></li>
              <li><a href="http://ietk.feri.um.si/">Inštitut za elektroniko in telekomunikacije</a></li>
              <li><a href="http://ii.uni-mb.si/">Inštitut za informatiko</a></li>
              <li><a href="http://www.pe.feri.uni-mb.si/podrocje.aspx">Inštitut za močnostno elektrotehniko</a></li>
              <li><a href="http://www.cs.feri.uni-mb.si/podrocje.aspx">Inštitut za računalništvo</a></li>
              <li><a href="http://www.ro.feri.uni-mb.si/portal/index.php">Inštitut za robotiko</a></li>
              <li><a href="http://www.mp.feri.uni-mb.si/">Inštitut za matematiko in fiziko</a></li>
              <li><a href="http://medijske.uni-mb.si/">Inštitut za medijske komunikacije</a></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span8">
            <?php $children = $this->viewModel()
                              ->getCurrent()
                              ->getChildren();
              $ourView  = $children[0];
              if (isset($ourView->flashMessages) && count($ourView->flashMessages)) : ?>
              <ul class="alert alert-info">
                  <?php foreach ($ourView->flashMessages as $fMessage) : ?>
                  <li><?php echo $fMessage; ?></li>
                  <?php endforeach; ?>
              </ul>
              <?php endif; ?>
            <?= $this->content; ?>
        </div><!--/span-->
        <div class="span2">
            <div class="desni-sidebar">
                <?php echo $this->sidebar() ?>
            </div>
        </div>
      </div><!--/row-->
    </div><!--/.fluid-container-->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <?= $this->inlineScript(); ?>
  </body>
</html>
